Mortgage_Calculator/Mortgage_Calculator/Models/MortgageInfo.cs
namespace Mortgage_Calculator.Models
{
    public class MortageInfo
    {
        public double Principal { get; set; }

        public double InterestRate { get; set; }

        public double DurationYears { get; set; }

        public double MonthlyPayment { get; set; }

        public string MortgageString { get; set; }
    }
}

Mortgage_Calculator/Mortgage_Calculator/Models/MortgageInfoDataAccess.cs
using System.Collections.Generic;

namespace Mortgage_Calculator.Models
{
    public class MortgageInfoDataAccess : IIOHelper
    {
        DatabaseIOHelper DatabaseIOHelper = new DatabaseIOHelper();

        public MortageInfo AddMortgage(MortgageModelInfo mortgageModelInfo)
        {
            MortageInfo mortgageInfo = new MortageInfo();
            mortgageInfo.Principal = mortgageModelInfo.Principal;
            mortgageInfo.InterestRate = mortgageModelInfo.InterestRate;
            mortgageInfo.DurationYears = mortgageModelInfo.DurationYears;
            mortgageInfo.MonthlyPayment = new MortgageHelper(mortgageModelInfo.Principal, mortgageModelInfo.InterestRate,
               mortgageModelInfo.DurationYears).ComputeMothlyPayment();

            mortgageInfo.MortgageString = $"With a principal of ${mortgageInfo.Principal}, duration of {mortgageInfo.DurationYears} years and an interest rate of {mortgageInfo.InterestRate}%, the monthly loan payment amount is ${mortgageInfo.MonthlyPayment}";

            AddMortgage(mortgageInfo.MortgageString, mortgageInfo.Principal, mortgageInfo.InterestRate,
                mortgageInfo.DurationYears, mortgageInfo.MonthlyPayment);

            return mortgageInfo;
        }

        public void AddMortgage(string formattedMortgageString, double principal, double interest, double years, double monthlypayment)
        {
            DatabaseIOHelper.AddMortgage(formattedMortgageString, principal, interest, years, monthlypayment);
        }

        public void ClearMortgages()
        {
            DatabaseIOHelper.ClearMortgages();
        }

        public List<MortageInfo> GetAllMortgages()
        {
            return DatabaseIOHelper.GetAllMortgages();
        }
    }
}

Mortgage_Calculator/Mortgage_Calculator/Models/MortgageModelInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Mortgage_Calculator.Models
{
    public class MortgageModelInfo
    {
        [Required]
        public double Principal { get; set; }

        [Required]
        [DisplayName("Rate of Interest(%)")]
        public double InterestRate { get; set; }

        [Required]
        [DisplayName("Duration in Years")]
        public double DurationYears { get; set; }
    }
}

Mortgage_Calculator/Mortgage_Calculator/Controllers/LoanAPIController.cs
using Mortgage_Calculator.Models;
using System.Collections.Generic;
using System.Web.Http;

namespace Mortgage_Calculator.Controllers
{
    public class LoanAPIController : ApiController
    {
        IIOHelper iOHelper = new MortgageInfoDataAccess();

        // GET: api/LoanAPI/getMonthlyPayment
        [HttpGet, ActionName("getMonthlyPayment")]
        public MortageInfo GetMonthlyPayment(MortgageModelInfo mortgageModelInfo)
        {
            MortgageInfoDataAccess mortgageInfoDataAccess = (MortgageInfoDataAccess)iOHelper;

            return mortgageInfoDataAccess.AddMortgage(mortgageModelInfo);
        }

        // GET: api/LoanAPI/getMortgagesList
        [HttpGet, ActionName("getMortgagesList")]
        public List<MortageInfo> GetMortgagesList()
        {
            MortgageInfoDataAccess mortgageInfoDataAccess = (MortgageInfoDataAccess)iOHelper;

            return mortgageInfoDataAccess.GetAllMortgages();
        }

        // DELETE: api/LoanAPI/deleteMortgages
        [HttpDelete, ActionName("deleteMortgages")]
        public void DeleteMortgages()
        {
            MortgageInfoDataAccess mortgageInfoDataAccess = (MortgageInfoDataAccess)iOHelper;
            mortgageInfoDataAccess.ClearMortgages();
        }
    }
}

Mortgage_Calculator/Mortgage_Calculator/Controllers/LoanController.cs
using Mortgage_Calculator.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Mortgage_Calculator.Controllers
{
    public class LoanController : Controller
    {
        IIOHelper iOHelper = new DatabaseIOHelper();
        LoanAPIController loanAPIController = new LoanAPIController();

        // GET: Loan
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index([Bind(Include = "Principal,InterestRate,DurationYears")] MortgageModelInfo mortgageModelInfo)
        {
            if (ModelState.IsValid)
            {
                var mortgageInfo = loanAPIController.GetMonthlyPayment(mortgageModelInfo);

                ViewBag.Message = mortgageInfo.MortgageString;

                return View("Details", mortgageInfo);
            }
            else
            {
                return View("Index", mortgageModelInfo);
            }
        }

        public ActionResult List()
        {
            List<MortageInfo> mortgageInfos = loanAPIController.GetMortgagesList();

            return View("List", mortgageInfos);
        }

        public ActionResult Delete()
        {
            return View("Delete");
        }

        [HttpPost]
        public ActionResult DeletePost()
        {
            loanAPIController.DeleteMortgages();

            ViewBag.Message = "Mortgage data has been cleared succesfully";

            return View("Delete");
        }
    }
}

Mortgage_Calculator/Mortgage_Calculator/Views/Loan/Delete.cshtml
@{
    ViewBag.Title = "Clear Mortgage Data";
}

<h2>Clear Mortgages</h2>

<div>
    <h5>@ViewBag.Message</h5>
</div>

@using (Html.BeginForm("DeletePost", "Loan"))
{
    @Html.AntiForgeryToken();

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    </div>
}

Mortgage_Calculator/Mortgage_Calculator/Views/Loan/Details.cshtml
@{
    ViewBag.Title = "Details";
}

<h2>Monthly Payment</h2>

<div>
    <h5>@ViewBag.Message</h5>
</div>

Mortgage_Calculator/Mortgage_Calculator/Views/Loan/Index.cshtml
@model Mortgage_Calculator.Models.MortgageModelInfo

@{
    ViewBag.Title = "Index";
}

<h2>Mortgage Monthly Payment Calculator</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Principal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Principal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Principal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterestRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterestRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterestRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DurationYears, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DurationYears, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DurationYears, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Compute" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mortgage_Calculator/Mortgage_Calculator/Views/Loan/List.cshtml
@model IEnumerable<Mortgage_Calculator.Models.MortageInfo>

@{
    ViewBag.Title = "View Monthly Payments";
}

<h2>List Monthly Payments</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Principal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InterestRate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DurationYears)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MonthlyPayment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MortgageString)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Principal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InterestRate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DurationYears)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MonthlyPayment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MortgageString)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
        </td>
    </tr>
}

</table>

Mortgage_Calculator/Mortgage_Calculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Monthly Payment Calculator", "Index", "Loan", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List Monthly Payments", "List")</li>
                    <li>@Html.ActionLink("Clear Monthly Payments", "Delete")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>